%% homePage.m
% Creates the layout for the home page.
function homePage()
    mainContainer = figure('Name', 'Device Localization in Wireless Systems', ...
        'NumberTitle', 'off', ...
        'Resize', 'off', ...
        'ToolBar', 'none', ...
        'Position', [500 500 1000 600] ...
    );
    
    documentationToolbar(mainContainer);

    % --- UI ---

    title();
    subtitle();

    titleImage(mainContainer);
    buttons(mainContainer);

    footer();
end

%% getLeftPad
% Get the left padding (left arg. for position params)
function pad = getLeftPad()
    pad = 80;
end

%% documentationToolbar
% Adds the "Documentation" toolbar item
function docsToolbar = documentationToolbar(mainContainer)
    docsToolbar = uimenu(mainContainer, 'Text', 'Documentation');

    % Open repo
    uimenu(docsToolbar, ...
        "Text", 'Open Repository on GitHub', ...
        "Accelerator",  'G', ...
        "Callback", 'web("https://github.com/Th3-Real-Alex/RC-Device-Localization-in-Wireless-Systems")' ...
    );

    % % Open .docx
    % uimenu(docsToolbar, ...
    %     "Text", 'Open Documentation - .docx', ...
    %     "Accelerator",  'D', ...
    %     "Separator", "on", ...
    %     "Callback", 'openDocs("docx")' ...
    % );
    % % Open .pdf
    % uimenu(docsToolbar, ...
    %     "Text", 'Open Documentation - .pdf', ...
    %     "Accelerator",  'P', ...
    %     "Callback", 'openDocs("pdf")' ...
    % );
end

%% title
% Adds the title to the page
function titleText = title()
    titleText = uicontrol('Style','text', ...
        'Fontsize', 38, ...
        'FontWeight', 'bold', ...
        'Position', [getLeftPad 410 500 100], ...
        'HorizontalAlignment', 'left', ...
        'String','Device Localization' ...
    );

end

%% subtitle
% Adds the title to the page
function subtitleText = subtitle()
    subtitleText = uicontrol('Style','text', ...
        'Fontsize', 18, ...
        'Position', [getLeftPad 360 500 100], ...
        'HorizontalAlignment', 'left', ...
        'String','Device Localization in Wireless Systems using TOA and TDOA measurements.' ...
    );

    uicontrol('Style','text', ...
        'Fontsize', 14, ...
        'Position', [getLeftPad 290 500 100], ...
        'HorizontalAlignment', 'left', ...
        'String','Available Experiments:' ...
    );
end

%% titleImage
% Adds the title image to the page
function titleImage(mainContainer)
    ax = uiaxes(mainContainer, ...
        'Position', [600 250 320 300], ...
        'Color', '#f0f0f0', ...
        'MinorGridLineStyle', 'none' ...
    );
    axis(ax, "off");
    [img, ~, alphachannel] = imread('lib/title.png');
    % Image Credit: https://www.mathworks.com/help/phased/ug/device-localization-in-wireless-systems.html
    image(img, 'AlphaData', alphachannel, 'Parent', ax);
end

%% buttons
% Adds the controls (push buttons) to the page, and registers their callbacks
function buttons(mainContainer)
    uicontrol('Style','pushbutton', ...
        'Fontsize', 14, ...
        'FontWeight', 'bold', ...
        'ForegroundColor', '#ed853d', ...
        'Position',[getLeftPad 300 400 50], ...
        'String','Target & Anchor Effects', ...
        'Callback', @(src, event) openTargetsAndAnchors(mainContainer) ...
    );

    uicontrol('Style','pushbutton', ...
        'Fontsize', 14, ...
        'FontWeight', 'bold', ...
        'ForegroundColor', '#ed853d', ...
        'Position',[getLeftPad 240 400 50], ...
        'String','Position Accuracy', ...
        'Callback', @(src, event) openPositionAccuracy(mainContainer) ...
    );

    uicontrol('Style','pushbutton', ...
        'Fontsize', 14, ...
        'FontWeight', 'bold', ...
        'ForegroundColor', '#ed853d', ...
        'Position',[getLeftPad 180 400 50], ...
        'String','Impact of invalid synchronization between anchors', ...
        'Callback', @(src, event) openImpactOfInvalidSync(mainContainer) ...
    );

    % uicontrol('Style','pushbutton', ...
    %     'Fontsize', 12, ...
    %     'ForegroundColor', '#0f3d8d', ...
    %     'Position',[getLeftPad 140 200 35], ...
    %     'String','Open Documentation (.docx)', ...
    %     'Callback', 'openDocs("docx")' ...
    % );
    % 
    % uicontrol('Style','pushbutton', ...
    %     'Fontsize', 12, ...
    %     'ForegroundColor', '#af0c02', ...
    %     'Position',[getLeftPad 100 200 35], ...
    %     'String','Open Documentation (.pdf)', ...
    %     'Callback', 'openDocs("pdf")' ...
    % );
end



%% footer
% Adds the footer text to the bottom of the page
function footer()
    uicontrol('Style','text', ...
        'Fontsize', 12, ...
        'Position',[0 0 1000 40], ...
        'String','David Pescariu & Cacuci Alexandru - Radio Communications Project' ...
    );
    uicontrol('Style','text', ...
        'Fontsize', 12, ...
        'Position',[0 0 1000 25], ...
        'Enable', 'inactive', ...
        'ButtonDownFcn', 'web("https://github.com/Th3-Real-Alex/RC-Device-Localization-in-Wireless-Systems")', ...
        'String','github.com/Th3-Real-Alex/RC-Device-Localization-in-Wireless-Systems' ...
    );
end