function targetsAndAnchors()
    pageContainer = uifigure('Name', 'Device Localization in Wireless Systems - Target & Anchor Effects', ...
        'NumberTitle', 'off', ...
        'Resize', 'off', ...
        'ToolBar', 'none', ...
        'Position', [500 500 1280 720] ...
    );
end